spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?serverTimezone=UTC
    username: root
    password: 4321@cbA
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


